# Date: 05 December 2020

## Question:
Given the following code what would be the output of last line?

```python
>>> number=10
>>> def print_number():
...     print(number)
...
>>> print_number()
10
>>> def add_one():
...     number = number + 1
...     print(number)
...
>>> add_one()
```

## Topic:
1. Programming
2. Python
3. Scope

## Options:
1. 101
2. 11
3. 1
4. Error

## Correct Option:
4. Error

## Explanation:
The last line would through an error, as the `number` is not defined in the function scope. As long as the local variable is not defined or changed, all will be fine, as in the case of function `print_number()`. But one cannot modify a global variable inside the function. At this point, python thinks that you are creating a new local variable.

```python
>>> number=10
>>> def add_one():
...     number = number + 1
...     print(number)
...
>>> add_one()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in add_one
UnboundLocalError: local variable 'number' referenced before assignment
```
To modify a global variable inside a function scope, one can use the keyword *global*.

```python
>>> number=10
>>> def add_one():
...     global number
...     number = number + 1
...     print(number)
...
>>> add_one()
11
```

## Scripts:
1. Question Script: NULL
2. Answer Script: NULL

## Link:
1. Question Link: NULL
2. Answer Link: NULL

## Images:
1. Question Images:
   1. "../images/questions/q_05122020.png" 
2. Answer Images:
   1. "../images/answers/a_05122020_1.png"
   2. "../images/answers/a_05122020_2.png" 
